# Generated by Django 6.0 on 2026-04-23 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Adminapp.school'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('type', 'department', 'school', 'subject_name')},
        ),
    ]
