# Generated by Django 6.0.4 on 2026-04-23 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_subject_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='school_class',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'school'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Adminapp.classes'),
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(choices=[('science', 'Science'), ('biology', 'Biology'), ('humanities', 'Humanities'), ('commerce', 'Commerce'), ('general', 'General')], max_length=20)),
                ('school_class', models.ForeignKey(limit_choices_to={'type': 'school'}, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='Adminapp.classes')),
            ],
            options={
                'unique_together': {('stream_name', 'school_class')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='Adminapp.stream'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('type', 'department', 'school', 'school_class', 'stream', 'subject_name')},
        ),
    ]
