# Generated by Django 6.0.4 on 2026-04-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_alter_subject_unique_together_subject_school_and_more'),
        ('Adminapp', '0005_subject_not_school_bound'),
    ]

    operations = [
    ]
