# Generated by Django 6.0.4 on 2026-04-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0006_merge_20260424_1550'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('type', 'department', 'school_class', 'stream', 'subject_name')},
        ),
    ]
