# Generated by Django 6.0.4 on 2026-04-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
        ('Guestapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classteacher',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='classteacher',
            name='course',
        ),
        migrations.RemoveField(
            model_name='classteacher',
            name='subject',
        ),
        migrations.AlterField(
            model_name='classteacher',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Adminapp.college'),
        ),
        migrations.AlterField(
            model_name='classteacher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Adminapp.department'),
        ),
        migrations.AlterField(
            model_name='classteacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Adminapp.school'),
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Guestapp.classteacher')),
            ],
            options={
                'unique_together': {('teacher', 'subject')},
            },
        ),
    ]
