# Generated by Django 6.0.4 on 2026-04-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0002_remove_classteacher_class_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherSubject',
        ),
    ]
