# Generated by Django 6.0.4 on 2026-04-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherapp', '0002_alter_post_author_alter_reply_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
