# Generated by Django 6.0.4 on 2026-04-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherapp', '0003_remove_reply_post_remove_reply_author_delete_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('homework', 'Homework'), ('assignment', 'Assignment'), ('seminar', 'Seminar'), ('testpaper', 'Test Paper')], max_length=20),
        ),
    ]
