# Generated by Django 6.0 on 2026-04-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherapp', '0003_remove_reply_post_remove_reply_author_delete_post_and_more'),
        ('Teacherapp', '0003_teachercourse_coursesection_coursenote_coursecomment_and_more'),
    ]

    operations = [
    ]
