# Generated by Django 6.0.4 on 2026-04-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherapp', '0005_studyrequest'),
        ('Teacherapp', '0006_courseassignment_section_coursenote_section'),
    ]

    operations = [
    ]
