# Generated by Django 6.0.4 on 2026-04-24 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherapp', '0007_merge_20260424_1551'),
        ('communityapp', '0004_alter_post_likes_alter_reply_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseassignment',
            name='section',
        ),
        migrations.RemoveField(
            model_name='coursenote',
            name='section',
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='progress_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_replies', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='communityapp.post')),
            ],
        ),
    ]
