# Generated by Django 6.0.4 on 2026-04-29 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherapp', '0008_remove_courseassignment_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Teacherapp.coursesection'),
        ),
        migrations.AddField(
            model_name='coursenote',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Teacherapp.coursesection'),
        ),
    ]
