# Generated by Django 6.0.4 on 2026-04-30 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0003_delete_teachersubject'),
        ('Teacherapp', '0009_courseassignment_section_coursenote_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Teacherapp.teachercourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_payments', to='Guestapp.student')),
            ],
            options={
                'unique_together': {('course', 'student')},
            },
        ),
    ]
