# Generated by Django 6.0.4 on 2026-05-04 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherapp', '0010_coursepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomment',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='is_instructor_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_course_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
