# Generated by Django 6.0.4 on 2026-05-04 09:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0003_delete_teachersubject'),
        ('Teacherapp', '0011_coursecomment_is_answered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='CourseReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reply', to='Teacherapp.coursereview')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_replies', to='Guestapp.classteacher')),
            ],
        ),
    ]
