# Generated by Django 6.0.4 on 2026-05-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherapp', '0012_alter_coursereview_rating_coursereviewreply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
