# Generated by Django 6.0.4 on 2026-05-19 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0003_delete_teachersubject'),
        ('Teacherapp', '0013_delete_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_collections', to='Guestapp.student')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudentCourseCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Teacherapp.studentcoursecollection')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_in_collections', to='Teacherapp.teachercourse')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('collection', 'course')},
            },
        ),
    ]
